# Generated by Django 5.1.3 on 2024-11-23 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelsdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
    ]
