# Generated by Django 5.1.3 on 2024-11-22 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsdb', '0005_student_blog_ox_personstatus_place_restaurant_waiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPerson',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('modelsdb.person',),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modelsdb.place')),
                ('customers', models.ManyToManyField(related_name='provider', to='modelsdb.place')),
            ],
            bases=('modelsdb.place',),
        ),
    ]
