# Generated by Django 5.1.3 on 2024-11-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsdb', '0007_piece_author_orderedperson_rename_slug_blog_tagline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data', models.JSONField(null=True)),
            ],
        ),
    ]
